from os.path import dirname, join


class AppConstant:

    PROJECT_ROOT = dirname(dirname(__file__))
    RESOURCE_FOLDER = join(PROJECT_ROOT, 'resources')
    DEFAULT_CONFIGS_FOLDER = join(RESOURCE_FOLDER, 'default_configs')
    TESTRAIL_CONFIG = join(RESOURCE_FOLDER, 'testrail.properties')
    SYSTEM_CONFIG = join(RESOURCE_FOLDER, 'system.properties')
    DEV_CONFIG = join(RESOURCE_FOLDER, 'dev.properties')
    DEMO_CONFIG = join(RESOURCE_FOLDER, 'demo.properties')
    STAGING_CONFIG = join(RESOURCE_FOLDER, 'staging.properties')
    PRODUCTION_CONFIG = join(RESOURCE_FOLDER, 'production.properties')
    DATA_CONFIG = join(RESOURCE_FOLDER, 'data.properties')
    JENKINS_CONFIG = join(RESOURCE_FOLDER,'jenkins.properties')
    TESTRAIL_CONFIG = join(RESOURCE_FOLDER, 'testrail.properties')
    IOS_REAL_DEVICE_CONFIG = join(RESOURCE_FOLDER, 'ios_real_device.properties')
    IOS_SIMULATOR_CONFIG = join(RESOURCE_FOLDER, 'ios_simulator.properties')
    ANDROID_REAL_DEVICE_CONFIG = join(RESOURCE_FOLDER, 'android_real_device.properties')
    JSON_DATA_FOLDER = join(RESOURCE_FOLDER, 'json_data')
    PAGE_OBJECTS_CONFIG_FILE = join(RESOURCE_FOLDER, 'page_objects.properties')
    SKIPPED_TESTCASES_FILE = join(RESOURCE_FOLDER, 'skipped_testcases.properties')
    XFAILED_TESTCASES_FILE = join(RESOURCE_FOLDER, 'xfailed_testcases.properties')
    ALLURE_ENV_FILE = join(RESOURCE_FOLDER, 'environment.properties')
    APK_FOLDER = join(RESOURCE_FOLDER, 'apk')
    CLIENT_CONFIG_FILE = join(RESOURCE_FOLDER, 'credentials/client_secrets.json')
    DOCKER_COMPOSE_FILE = join(RESOURCE_FOLDER, 'docker-compose.yml')
    DOCKER_COMPOSE_TEMPLATE_FILE = join(RESOURCE_FOLDER, 'docker-compose-template.yml')
    CLIENT_CONFIG_FILE = join(RESOURCE_FOLDER, 'credentials/client_secrets.json')
    GOOGLE_CREDENTIAL_FILE = join(RESOURCE_FOLDER, 'credentials/google_saved_credentials.txt')
    LAMBDATEST_CONFIG = join(RESOURCE_FOLDER, 'lambdatest.properties')
    JENKINS_CONFIG = join(RESOURCE_FOLDER,'jenkins.properties')
    JIRA_CONFIG = join(RESOURCE_FOLDER, 'jira.properties')
    IOS_CAPABILITIES_CONFIGS = join(RESOURCE_FOLDER, 'device_capabilities/ios_capabilities.json')
    TEST_STEPS_FOLDER = join(RESOURCE_FOLDER, 'test_steps')
    REQUEST_DATA_FOLDER = join(RESOURCE_FOLDER, 'request_data')
    JENKINS_CONFIG = join(RESOURCE_FOLDER, 'jenkins.properties')

