name: Go Notebuilder Base Workflow

on:
  push:
    branches:
      - Go_Notebuilder_Base
  pull_request:
    branches:
      - Go_Notebuilder_Base

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add additional steps here as needed, such as running tests or deployments
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
